SupporTix/SupporTix/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SupporTix.Models
{
    public class Ticket
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string Name { get; set; }

        [Required]
        [MaxLength(50)]
        public string Facility { get; set; }

        [Required]
        [MaxLength(100)]
        public string Email { get; set; }

        [Required]
        [MaxLength(20)]
        public string Phone { get; set; }

        [Required]
        public string RequestType { get; set; }

        [Required]
        [MaxLength(1000)]
        public string Details { get; set; }
    }
}

SupporTix/SupporTix/ViewModels/NewTicketViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SupporTix.Models;

namespace SupporTix.ViewModels
{
    public class NewTicketViewModel
    {
        public IEnumerable<RequestType> RequestTypes { get; set; }
        public Ticket Ticket { get; set; }
    }
}

SupporTix/SupporTix/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SupporTix.Models;
using SupporTix.ViewModels;

namespace SupporTix.Controllers
{
    public class TicketsController : Controller
    {
        private ApplicationDbContext _context;

        public TicketsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Tickets
        public ActionResult Index()
        {
            return View();
        }

        //GET: NewTicket
        public ActionResult NewTicket()
        {
            var requestTypes = _context.RequestTypes.ToList();
            var viewModel = new NewTicketViewModel
            {
                RequestTypes = requestTypes
            };

            return View(viewModel);
        }

        //POST: Create
        public ActionResult Create(Ticket ticket)
        {
            _context.Tickets.Add(ticket);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

SupporTix/SupporTix/Views/Tickets/NewTicket.cshtml
@model SupporTix.ViewModels.NewTicketViewModel
@{
    ViewBag.Title = "NewTicket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Ticket</h2>

@using (@Html.BeginForm("Create", "Tickets"))
{
    @Html.ValidationSummary(true, "Please fix the following errors.")
    <div class="form-group">
        @Html.LabelFor(t => t.Ticket.Name)
        @Html.TextBoxFor(t => t.Ticket.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Ticket.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Ticket.Facility)
        @Html.TextBoxFor(t => t.Ticket.Facility, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Ticket.Facility)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Ticket.Email)
        @Html.TextBoxFor(t => t.Ticket.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Ticket.Email)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Ticket.Phone)
        @Html.TextBoxFor(t => t.Ticket.Phone, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Ticket.Phone)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Ticket.RequestType)
        @Html.DropDownListFor(t => t.Ticket.RequestType, new SelectList(Model.RequestTypes, "Id", "Name"), "Select One", new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Ticket.RequestType)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Ticket.Details)
        @Html.TextAreaFor(t => t.Ticket.Details, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Ticket.Details)
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}